version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0 #Heroku orb
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    executor: docker/docker #State the environment  that we are using
    steps:
      - setup_remote_docker #This allows use to run docker commands just in case
      - checkout
      - docker/check
      - docker/build:
          image: pcwz/educational-space
          tag: 1.0.1
      - docker/push:
          image: pcwz/educational-space
          tag: 1.0.1

  depoly:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install #installs heroku cli for our run command
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a pcwz-su-devops
            heroku container:release web -a pcwz-su-devops
          #the push command pushes the image to heroku's container registry
          #The release command deploys the image from heroku's container registry
          #the name of the group of commans we are running
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
        requires:
          - build-and-push
